#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Clean Build
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B clean # -B batch mode makes Maven less verbose
    - step:
        name: Compile build
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B compile # -B batch mode makes Maven less verbose
    - step:
        name: Package build
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B package # -B batch mode makes Maven less verbose