#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.3.9



pipelines:
  default:
    - step:
        image: openjdk:11
        caches:
          - maven
        script:
          - mvn -B verify

