POST http://localhost:8080/reviewers
Content-Type: application/json

{
  "id": 0,
  "name": "233",
  "password": "322",
  "email": "23111",
  "address": "string",
  "institutionId": 1
}

###

POST http://localhost:8080/students
Content-Type: application/json

{
  "id": 0,
  "name": "student",
  "password": "student",
  "email": "student",
  "address": "string",
  "institutionId": 1
}
