
###
POST http://localhost:8080/institutions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwiZXhwIjoxNjA4NDI2MTkxLCJpYXQiOjE2MDg0MjU1OTEsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dLCJ1c2VybmFtZSI6ImFkbWluIn0.eFwkYxpFqi7HOauIcyMF29wvnPdctw5CdMev8GQDSaY
Content-Type: application/json

{
  "id": 0,
  "name": "FCT",
  "contact": "FCT"
}

###

GET http://localhost:8080/institutions
Accept: application/json

###

POST http://localhost:8080/reviewers
Content-Type: application/json

{
  "id": 0,
  "name": "string",
  "password": "string",
  "email": "string",
  "address": "string",
  "institutionId": 1
}

###

GET http://localhost:8080/reviewers
Accept: application/json

###

POST http://localhost:8080/students
Content-Type: application/json

{
  "id": 0,
  "name": "string",
  "password": "string",
  "email": "string",
  "address": "string",
  "institutionId": 1
}

###
GET http://localhost:8080/students
Accept: application/json

