POST http://localhost:8080/login
Content-Type: application/json

{
  "name": "sponsor22",
  "password": "sponsor22"
}

###

POST http://localhost:8080/signup
Content-Type: application/json

{
  "name": "sponsor22",
  "password": "sponsor22"
}

###
POST http://localhost:8080/signup
Content-Type: application/json

{
  "id": 0,
  "name": "sponsor22",
  "contact": "FCT22",
  "password": "sponsor22",
  "email": "fct@gmail2.com2",
  "address": "Rua fct22",
  "type": "Sponsor"
}
###
POST http://localhost:8080/signup
Content-Type: application/json

{
"id": 0,
"name": "233312312dasdasdasdadasdas",
"password": "322321312",
"email": "23111321312312dasdasdasdasdasdasdas",
"address": "string",
"institutionId": 1,
  "type": "Reviewer"
}
###
POST http://localhost:8080/signup
Content-Type: application/json

{
  "id": 0,
  "name": "studentdasdasdas321312312",
  "password": "student",
  "email": "studentdasdasdas321312312",
  "address": "string",
  "institutionId": 1,
  "type": "Student"
}


###

GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwiZXhwIjoxNjA2NTk3ODMyLCJpYXQiOjE2MDY1NjE4MzIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1NQT05TT1IifV0sInVzZXJuYW1lIjoic3BvbnNvcjIyIn0.riNxgUsPEY6SksiagjmUZEdzhnnKfuCiXAVsXvud_1k
Content-Type: application/json

###

POST http://localhost:8080/grantcalls
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwiZXhwIjoxNjA2NjEwMDQ2LCJpYXQiOjE2MDY1NzQwNDYsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1NQT05TT1IifV0sInVzZXJuYW1lIjoic3BvbnNvcjIyIn0.nygcMgZ4I3lTTSZw0CP7QnSnaIa7yy6nN0o0JXSKHms
Content-Type: application/json


{
  "id": "0",
  "title" : "GrantCall #1",
  "description" : "A grantcall",
  "requirements" : "requirements",
  "funding": "500",
  "openingDate": "Fri, 27 Nov 2020 15:32:46 GMT",
  "closingDate": "Fri, 27 Nov 2020 15:32:46 GMT",
  "dataItems": [{
    "mandatory": "true",
    "name": "name",
    "datatype": "string"
  },
    {
      "mandatory": "true",
      "name": "name",
      "datatype": "string"
    },
    {
      "mandatory": "true",
      "name": "name",
      "datatype": "string"
    },
    {
      "mandatory": "true",
      "name": "name",
      "datatype": "string"
    },
    {
      "mandatory": "true",
      "name": "name",
      "datatype": "string"
    }

  ],
  "sponsorId": "1",
  "evaluationPanelId": -1
}

###

GET http://localhost:8080/grantcalls/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwiZXhwIjoxNjA2NTk4Mzk5LCJpYXQiOjE2MDY1NjIzOTksImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1NQT05TT1IifV0sInVzZXJuYW1lIjoic3BvbnNvcjIyIn0.aBY8krgkb0ZfAi2EyZW3nSZWyB9Rf3YEFMB9sYRHZ1o
Content-Type: application/json
